version: '3'
services:
  app1:
    build: ./app
    ports:
      - "5001:5000"
  app2:
    build: ./app
    ports:
      - "5002:5000"
  app3:
    build: ./app
    ports:
      - "5003:5000"
  app4:
    build: ./app
    ports:
      - "5004:5000"
  app5:
    build: ./app
    ports:
      - "5005:5000"          
  app6:
    build: ./app
    ports:
      - "5006:5000"     
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - app1
      - app2
      - app3
      - app4